version: "3.9"
services:
  Database:
    container_name: DatabaseService
    image: postgres:latest
    enviroment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - yt_fetcher_volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - yt_fetcher_network

  Bot:
    container_name: BotService
    image: yt_fetcher_tgbot
    enviroment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    secrets:
      - yt_api_keys
      - tg_api_key
    networks:
      - yt_fetcher_network

  Filter:

volumes:
  yt_fetcher_volume

networks:
  yt_fetcher_network:
    driver: bridge

secrets:
  yt_api_keys:
    file: ./yt_api_keys
  tg_api_key:
    file: ./tg_api_key

