version: "3.9"
services:
  Database:
    container_name: DatabaseService
    image: postgres:latest
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - yt_fetcher_volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - yt_fetcher_network
    restart: unless-stopped

  Bot:
    container_name: BotService
    image: yt_fetcher_tgbot
    environment:
      POSTGRES_DB: "app_db"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    secrets:
      - yt_api_keys
      - bot_token
      - bot_password
    networks:
      - yt_fetcher_network
    restart: unless-stopped

  Filter:
    container_name: FilterService
    image: yt_fetcher_filter
    networks:
      - yt_fetcher_network
    restart: unless-stopped

volumes:
  yt_fetcher_volume:

networks:
  yt_fetcher_network:
    driver: bridge

secrets:
  yt_api_keys:
    file: ./yt_api_keys
  bot_token:
    file: ./bot_token
  bot_password:
    file: ./bot_password
